name: Generate Snake GIF for Contributions
on:
  push:
    branches:
      - main

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Generate Snake GIF
        uses: Platane/snk@v3
        with:
          github_user_name: 'Zain523'
          # Specify output paths
          output: dist/github-contribution-snake.svg
          dark_output: dist/github-contribution-snake-dark.svg
          gif_output: dist/github-contribution-snake.gif
          color_snake: 'orange'
          color_dots: '#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9'
